### ISSUE TITLE
Clarify License in Cargo.toml

### ISSUE THREAD

**Issue by xanderlent** [danielhenrymantilla/macro_rules_attribute-rs#26]
Thank you for providing this crate as open source! I'm working to package it for Fedora Linux, which is particular about License information.

Is this crate intended to be licensed under the user's choice of MIT OR Apache-2.0 OR Zlib, or is licensed under some other combination of these three licenses? Originally the LICENSE file was the MIT License, but in commit 8c93517dd9623d7d02dbda19f3bb4f0d0d10a93f the other two LICENSE files were added.

Currently all three `LICENSE-*` files are included in both of the crates generated by this repo.
However, the Cargo.toml files for both crates include only:
```toml
[package]
license = "MIT"
```

If you'd like, I can submit a PR changing that to:
```toml
[package]
license = "MIT OR Apache-2.0 OR Zlib"
```
